#!/usr/bin/env bash
# Usage: gt current-weather
# Summary: Prints your current weather from Yahoo Weather
# Help: This command prints your current weather from Yahoo Weather.
#
# Example:
#
#     Partly Cloudy, 25 F

curl --silent "http://xml.weather.yahoo.com/forecastrss?p=USNY0082&u=f" |
  grep -E '(Current Conditions:|F<BR)' |
  sed -e 's/Current Conditions://' \
      -e 's/<br \/>//' \
      -e 's/<b>//' \
      -e 's/<\/b>//' \
      -e 's/<BR \/>//' \
      -e 's///' \
      -e 's/<\/description>//' |
  tail -1
