#!/usr/bin/env bash
# Usage: gt itunes-lyrics
# Summary: Prints lyrics from the song currently playing in iTunes
# Help: This command prints lyrics from the song currently playing in iTunes.
# It queries <http://makeitpersonal.co/lyrics> to find lyrics for the song.
#
# Credit to @febuiles <https://gist.github.com/1549979>

artist=`osascript -e'tell application "iTunes"' -e'get artist of current track' -e'end tell'`
title=`osascript -e'tell application "iTunes"' -e'get name of current track' -e'end tell'`

song=`curl -G --data-urlencode "artist=$artist" \
  --data-urlencode "title=$title" -s http://makeitpersonal.co/lyrics`

echo -e "$artist - $title\n$song"
