#!/usr/bin/env bash
# Usage: gt top-processes
# Summary: Prints a list of processes sorted by memory
# Help: This command prints a list processes sorted by most-used memory.

echo "TOP PROCESSES:"
ps -Aro'%cpu, ucomm, user' | grep `whoami` | grep -v '  0.0 ' | more +1
